export const textOverlayTemplates: Record<string, any> = {
  modern: {
    name: "Modern Title",
    content: "Modern Title",
    preview: "Sleek & Minimalist",
    styles: {
      fontSize: "2.8rem",
      fontWeight: "700",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.1",
      textAlign: "center",
      letterSpacing: "-0.03em",
    },
  },
  impact: {
    name: "Impact Statement",
    content: "MAKE AN IMPACT",
    preview: "Bold & Commanding",
    styles: {
      fontSize: "3.5rem",
      fontWeight: "900",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.02em",
      textTransform: "uppercase",
      textShadow: "2px 2px 0px rgba(0, 0, 0, 0.2)",
    },
  },
  slicedText: {
    name: "Sliced Text",
    content: "SLICED",
    preview: "Edgy & Modern",
    isPro: true,
    styles: {
      fontSize: "4.2rem",
      fontWeight: "900",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      textShadow: "6px 6px 0px #FF2D55, -6px -6px 0px #5E5CE6",
    },
  },
  minimalMonochrome: {
    name: "Minimal Monochrome",
    content: "less is more",
    preview: "Ultra Minimal",
    styles: {
      fontSize: "3rem",
      fontWeight: "200",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.25em",
      textTransform: "lowercase",
      border: "1px solid rgba(255, 255, 255, 0.3)",
      padding: "24px 48px",
    },
  },
  highlight: {
    name: "Highlight Box",
    content: "Highlighted Text",
    preview: "Modern & Distinctive",
    styles: {
      fontSize: "2.4rem",
      fontWeight: "700",
      color: "#FFFFFF",
      backgroundColor: "rgba(79, 70, 229, 0.85)",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      padding: "16px 32px",
      borderRadius: "12px",
      textAlign: "center",
      boxShadow:
        "0 8px 16px -4px rgba(79, 70, 229, 0.25), 0 4px 6px -2px rgba(0, 0, 0, 0.1)",
      backdropFilter: "blur(8px)",
      border: "1px solid rgba(255, 255, 255, 0.1)",
    },
  },
  gradient: {
    name: "Gradient Pop",
    content: "Gradient Style",
    preview: "Dynamic & Modern",
    isPro: true,
    styles: {
      fontSize: "3.2rem",
      fontWeight: "800",
      background:
        "linear-gradient(135deg, #6366F1 0%, #EC4899 50%, #F59E0B 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.1",
      textAlign: "center",
      textShadow: "0px 0px 20px rgba(236, 72, 153, 0.3)",
    },
  },
  neonFuture: {
    name: "Neon Future",
    content: "NEON FUTURE",
    preview: "Electric & Bold",
    styles: {
      fontSize: "3.2rem",
      fontWeight: "800",
      color: "#FFFFFF",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      textShadow: "0 0 10px #00FFFF, 0 0 20px #00FFFF, 0 0 30px #00FFFF",
      padding: "12px",
      border: "2px solid #00FFFF",
      borderRadius: "4px",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
  },
  avantGarde: {
    name: "Avant-Garde",
    content: "AVANT-GARDE",
    preview: "Fashion Forward",
    isPro: true,
    styles: {
      fontSize: "3.6rem",
      fontWeight: "900",
      background: "linear-gradient(90deg, #FFFFFF 50%, #000000 50%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      padding: "8px",
      textShadow: "4px 4px 0px rgba(0, 0, 0, 0.1)",
    },
  },
  glassmorphic: {
    name: "Glassmorphic",
    content: "GLASS EFFECT",
    preview: "Modern Transparency",
    styles: {
      fontSize: "3rem",
      fontWeight: "700",
      color: "#FFFFFF",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      textAlign: "center",
      letterSpacing: "0.1em",
      padding: "24px 48px",
      borderRadius: "16px",
      backdropFilter: "blur(10px)",
      border: "1px solid rgba(255, 255, 255, 0.2)",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    },
  },
  retro80s: {
    name: "Retro 80s",
    content: "RETRO VIBES",
    preview: "Nostalgic & Vibrant",
    styles: {
      fontSize: "3.4rem",
      fontWeight: "800",
      background: "linear-gradient(180deg, #FF6B9D 0%, #C06C84 50%, #6C5B7B 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontFamily: "font-sans",
      fontStyle: "italic",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.08em",
      textTransform: "uppercase",
      textShadow: "3px 3px 0px #000000",
    },
  },
  neonGlow: {
    name: "Neon Glow",
    content: "NEON GLOW",
    preview: "Glowing Effect",
    styles: {
      fontSize: "3.8rem",
      fontWeight: "700",
      color: "#FF10F0",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      textShadow: "0 0 5px #FF10F0, 0 0 10px #FF10F0, 0 0 20px #FF10F0, 0 0 40px #FF10F0",
    },
  },
  elegantScript: {
    name: "Elegant Script",
    content: "Elegance",
    preview: "Sophisticated & Refined",
    styles: {
      fontSize: "3.5rem",
      fontWeight: "400",
      color: "#D4AF37",
      fontFamily: "font-serif",
      fontStyle: "italic",
      textDecoration: "none",
      lineHeight: "1.3",
      textAlign: "center",
      letterSpacing: "0.02em",
      textShadow: "1px 1px 2px rgba(0, 0, 0, 0.3)",
    },
  },
  pixelArt: {
    name: "Pixel Art",
    content: "PIXEL",
    preview: "Retro Gaming",
    styles: {
      fontSize: "4rem",
      fontWeight: "900",
      color: "#00FF00",
      fontFamily: "monospace",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.1em",
      textTransform: "uppercase",
      textShadow: "4px 4px 0px #000000",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      padding: "16px 24px",
      border: "4px solid #00FF00",
    },
  },
  cinematic: {
    name: "Cinematic",
    content: "CINEMATIC",
    preview: "Movie Title Style",
    styles: {
      fontSize: "3.6rem",
      fontWeight: "900",
      color: "#FFFFFF",
      fontFamily: "font-serif",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "0.9",
      textAlign: "center",
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      textShadow: "0 2px 10px rgba(0, 0, 0, 0.8)",
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      padding: "20px 40px",
    },
  },
  comicBook: {
    name: "Comic Book",
    content: "POW!",
    preview: "Action Packed",
    styles: {
      fontSize: "4.5rem",
      fontWeight: "900",
      color: "#FFFF00",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      textShadow: "3px 3px 0px #000000, -2px -2px 0px #FF0000",
      WebkitTextStroke: "2px #000000",
    },
  },
  watercolor: {
    name: "Watercolor",
    content: "Watercolor",
    preview: "Artistic & Soft",
    styles: {
      fontSize: "3.2rem",
      fontWeight: "600",
      background: "linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontFamily: "font-serif",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      textAlign: "center",
      letterSpacing: "0.05em",
      filter: "blur(0.5px)",
    },
  },
  metallic: {
    name: "Metallic",
    content: "METALLIC",
    preview: "Chrome Effect",
    styles: {
      fontSize: "3.8rem",
      fontWeight: "900",
      background: "linear-gradient(180deg, #B8B8B8 0%, #7E7E7E 50%, #B8B8B8 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.1em",
      textTransform: "uppercase",
      textShadow: "1px 1px 2px rgba(0, 0, 0, 0.5)",
    },
  },
  graffiti: {
    name: "Graffiti",
    content: "STREET ART",
    preview: "Urban Style",
    styles: {
      fontSize: "3.5rem",
      fontWeight: "900",
      color: "#FF6B35",
      fontFamily: "font-sans",
      fontStyle: "italic",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.02em",
      textTransform: "uppercase",
      textShadow: "2px 2px 0px #000000, 4px 4px 0px #FFFF00",
      WebkitTextStroke: "1px #000000",
    },
  },
  minimalistBold: {
    name: "Minimalist Bold",
    content: "BOLD",
    preview: "Clean & Strong",
    styles: {
      fontSize: "4rem",
      fontWeight: "900",
      color: "#000000",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      backgroundColor: "#FFFFFF",
      padding: "20px 40px",
    },
  },
  typewriter: {
    name: "Typewriter",
    content: "Typewriter",
    preview: "Classic Typography",
    styles: {
      fontSize: "2.8rem",
      fontWeight: "400",
      color: "#333333",
      fontFamily: "monospace",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.4",
      textAlign: "center",
      letterSpacing: "0.1em",
      backgroundColor: "#F5F5DC",
      padding: "24px 32px",
      border: "2px solid #333333",
    },
  },
  futuristic: {
    name: "Futuristic",
    content: "FUTURE",
    preview: "Sci-Fi Style",
    styles: {
      fontSize: "3.6rem",
      fontWeight: "700",
      color: "#00D9FF",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.2em",
      textTransform: "uppercase",
      textShadow: "0 0 10px #00D9FF, 0 0 20px #00D9FF",
      border: "2px solid #00D9FF",
      padding: "16px 32px",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
    },
  },
  handwritten: {
    name: "Handwritten",
    content: "Handwritten",
    preview: "Personal Touch",
    styles: {
      fontSize: "3rem",
      fontWeight: "400",
      color: "#2C3E50",
      fontFamily: "cursive",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.3",
      textAlign: "center",
      letterSpacing: "0.02em",
    },
  },
  neonOutline: {
    name: "Neon Outline",
    content: "OUTLINE",
    preview: "Outlined Effect",
    styles: {
      fontSize: "4rem",
      fontWeight: "900",
      color: "transparent",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      WebkitTextStroke: "2px #FF00FF",
      textShadow: "0 0 15px #FF00FF, 0 0 30px #FF00FF",
    },
  },
  vintage: {
    name: "Vintage",
    content: "VINTAGE",
    preview: "Retro Classic",
    styles: {
      fontSize: "3.2rem",
      fontWeight: "700",
      color: "#D4A574",
      fontFamily: "font-serif",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      textAlign: "center",
      letterSpacing: "0.1em",
      textTransform: "uppercase",
      textShadow: "2px 2px 4px rgba(0, 0, 0, 0.5)",
      backgroundColor: "rgba(44, 30, 20, 0.8)",
      padding: "20px 40px",
      border: "3px solid #D4A574",
    },
  },
  holographic: {
    name: "Holographic",
    content: "HOLOGRAM",
    preview: "Iridescent Effect",
    styles: {
      fontSize: "3.5rem",
      fontWeight: "800",
      background: "linear-gradient(45deg, #FF0080, #FF8C00, #40E0D0, #FF0080)",
      backgroundSize: "300% 300%",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.08em",
      textTransform: "uppercase",
      animation: "gradient 3s ease infinite",
    },
  },
  embossed: {
    name: "Embossed",
    content: "EMBOSSED",
    preview: "3D Relief",
    styles: {
      fontSize: "3.8rem",
      fontWeight: "900",
      color: "#CCCCCC",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      textShadow: "1px 1px 1px #FFFFFF, -1px -1px 1px #000000",
      backgroundColor: "#999999",
      padding: "20px 40px",
    },
  },
  gamer: {
    name: "Gamer",
    content: "GAME ON",
    preview: "Gaming Style",
    styles: {
      fontSize: "3.6rem",
      fontWeight: "900",
      background: "linear-gradient(90deg, #00FF00 0%, #00FFFF 50%, #FF00FF 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontFamily: "font-sans",
      fontStyle: "italic",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      WebkitTextStroke: "1px rgba(0, 0, 0, 0.5)",
    },
  },
  luxury: {
    name: "Luxury",
    content: "LUXURY",
    preview: "Premium & Elegant",
    styles: {
      fontSize: "3.4rem",
      fontWeight: "700",
      color: "#FFD700",
      fontFamily: "font-serif",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      textAlign: "center",
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      textShadow: "2px 2px 4px rgba(0, 0, 0, 0.8), 0 0 10px #FFD700",
      backgroundColor: "rgba(0, 0, 0, 0.9)",
      padding: "24px 48px",
      border: "2px solid #FFD700",
    },
  },
  playful: {
    name: "Playful",
    content: "Fun & Playful!",
    preview: "Cheerful & Bouncy",
    styles: {
      fontSize: "3.2rem",
      fontWeight: "800",
      color: "#FF6B9D",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      textAlign: "center",
      letterSpacing: "0.03em",
      textShadow: "3px 3px 0px #FFD93D, -2px -2px 0px #6BCF7F",
      transform: "rotate(-2deg)",
    },
  },
};
